# https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: update-index

on:
  workflow_dispatch:
  schedule:
    # run at 15:00 UTC every day (8am PDT/UTC-7)
    - cron: '0 15 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: run actions/checkout@v2
        uses: actions/checkout@v2

      - name: run actions/setup-python@v2
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: run pip install -r maintenance/requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r maintenance/requirements.txt
          
      - name: run python maintenance/github-crawler.py
        run: python maintenance/github-crawler.py
          
      - name: run git commit -am "update index [ci skip]" 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -am "update index [ci skip]" 
          
      - name: run ad-m/github-push-action@v0.6.0
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
  
